# Generated by Django 4.2.4 on 2023-08-10 00:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('challenger', 'Challenger'), ('player', 'Player')], max_length=10)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_as_challenger', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_as_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('player_comment', models.TextField(blank=True)),
                ('challenger_comment', models.TextField(blank=True)),
                ('sent_by_player', models.BooleanField(default=False)),
                ('proof', models.FileField(blank=True, upload_to='task_proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('completed', models.BooleanField(default=False)),
                ('limit_date', models.DateField(blank=True, null=True)),
                ('last_sent_date', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.challenge')),
            ],
        ),
    ]
